# Generated by Django 3.1.7 on 2021-02-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.DateField(null=True, verbose_name='Дата выхода'),
        ),
    ]
